[package]
name = "token_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soroban-sdk = { version = "0.8.4" }
soroban-token-sdk = { version = "0.8.4" }
